import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faSearch,
  faHome,
  faPhotoVideo,
  faUsers,
  faObjectGroup,
  faPlus,
  faEnvelope,
  faBell,
  faCaretDown,
  faExclamationCircle,
  faCog,
  faQuestionCircle,
  faMoon,
  faSignOutAlt,
  faEllipsisH,
  faSave,
  faEyeSlash,
  faClock,
  faTimesCircle,
  faExclamationTriangle,
  faVideo,
  faLaugh,
} from "@fortawesome/free-solid-svg-icons";
import {
  faThumbsUp,
  faComment,
  faShareSquare,
} from "@fortawesome/free-regular-svg-icons";

export {
  FontAwesomeIcon,
  faSearch,
  faHome,
  faPhotoVideo,
  faUsers,
  faObjectGroup,
  faPlus,
  faEnvelope,
  faBell,
  faCaretDown,
  faExclamationCircle,
  faCog,
  faQuestionCircle,
  faMoon,
  faSignOutAlt,
  faEllipsisH,
  faSave,
  faEyeSlash,
  faClock,
  faTimesCircle,
  faExclamationTriangle,
  faThumbsUp,
  faComment,
  faShareSquare,
  faVideo,
  faLaugh,
};
